package viaduct.graphql.schema.validation.rules

import viaduct.graphql.schema.ViaductSchema
import viaduct.graphql.schema.validation.SchemaLocation
import viaduct.graphql.schema.validation.ValidationContext
import viaduct.graphql.schema.validation.ValidationErrorCodes
import viaduct.graphql.schema.validation.ValidationRule

/**
 * Validates that PageInfo is not defined inside a module partition.
 *
 * PageInfo is a framework-level type that belongs in the application schemabase
 * (src/main/viaduct/schemabase/) or is auto-generated by Viaduct when absent.
 * Defining it inside a tenant module partition creates an invisible cross-module
 * coupling: any connection type in another module depends on a type it cannot see.
 */
class PageInfoLocationRule(
    private val modulePathPrefix: String = "partition/"
) : ValidationRule(
        id = "PageInfoLocation",
        description = "PageInfo must not be defined inside a module partition"
    ) {
    override fun visitObject(
        ctx: ValidationContext,
        obj: ViaductSchema.Object
    ) {
        if (obj.name != PAGE_INFO_TYPE_NAME) return

        val baseExtension = obj.extensions.firstOrNull { it.isBase } ?: return
        val moduleName = tenantFromLocation(baseExtension.sourceLocation, modulePathPrefix) ?: return

        ctx.reportError(
            code = ValidationErrorCodes.PAGE_INFO_DEFINED_IN_MODULE,
            message = "PageInfo must not be defined in a module partition (found in module '$moduleName'). " +
                "Define it in src/main/viaduct/schemabase/ instead, or omit it entirely " +
                "and Viaduct will generate the standard Relay definition automatically.",
            location = SchemaLocation.ofType(PAGE_INFO_TYPE_NAME).withSourceLocation(baseExtension.sourceLocation)
        )
    }

    companion object {
        private const val PAGE_INFO_TYPE_NAME = "PageInfo"
    }
}
