package viaduct.engine.api.bootstrap.executionregistry

import java.util.Collections
import viaduct.bootstrap.ConfigKey
import viaduct.bootstrap.ExecutionRegistryConfigFile
import viaduct.bootstrap.SelectionsBlockConfig
import viaduct.service.api.spi.InputStreamSource

/** A parsed registry snapshot with its original source retained for diagnostics. */
data class ModuleConfigSource private constructor(
    val tenantName: String,
    val apiName: String,
    val source: InputStreamSource,
    val config: ExecutionRegistryConfigFile,
) {
    /**
     * This source's configuration key.
     *
     * Every place that decides "is this the same configuration?" — duplicate rejection, hotswap
     * replacement — keys off this. Code that deliberately groups more coarsely (e.g.
     * `ModuleConfigBootstrapper`, which scopes code injectors per tenant module) projects the
     * narrower field explicitly, which is what makes that choice visible rather than looking like
     * an incomplete version of this one.
     */
    val key: ConfigKey get() = ConfigKey(tenantName, apiName)

    companion object {
        /** Reads and validates the source once; consumers share the immutable parsed config. */
        fun from(source: InputStreamSource): ModuleConfigSource {
            val config = source.openStream().use { ExecutionRegistryConfigFile.parse(it) }
            val tenantName = config.tenantName
                ?: throw IllegalArgumentException("Execution registry config source must include tenantName: $source")
            val apiName = config.apiName?.takeIf { it.isNotBlank() }
                ?: throw IllegalArgumentException(
                    "Execution registry config source must include a non-blank apiName: $source. " +
                        "A config missing it was generated by a build predating the field; when this " +
                        "surfaces while overlaying sources onto a running process, restart that process " +
                        "on a newer build instead of overlaying onto it.",
                )
            return ModuleConfigSource(
                tenantName = tenantName,
                apiName = apiName,
                source = source,
                config = config.immutableSnapshot(),
            )
        }

        /**
         * Requires that [sources] contains at most one source per [ConfigKey], returning an
         * immutable copy of the list.
         *
         * Duplicate keys are malformed build inputs: two sources claiming one configuration slot
         * cannot both be materialized, and resolving the collision by list order would make which
         * resolvers get registered depend on discovery order. Distinct from resolver-coordinate
         * validation, which handles conflicts between *different* keys.
         *
         * @throws IllegalArgumentException if any key appears more than once.
         */
        fun requireUniqueKeys(sources: List<ModuleConfigSource>): List<ModuleConfigSource> {
            val duplicates = sources.groupBy { it.key }.filterValues { it.size > 1 }
            require(duplicates.isEmpty()) {
                val detail = duplicates.entries.joinToString("; ") { (key, dupes) ->
                    "$key from ${dupes.map { it.source }}"
                }
                "Duplicate execution registry config sources for the same <tenantName, apiName>: $detail"
            }
            return Collections.unmodifiableList(sources.toList())
        }

        private fun ExecutionRegistryConfigFile.immutableSnapshot(): ExecutionRegistryConfigFile =
            copy(
                nodes = Collections.unmodifiableList(nodes.map { it.copy(tenantAPIData = it.tenantAPIData.immutableJsonMap()) }),
                fields = Collections.unmodifiableList(
                    fields.map {
                        it.copy(
                            tenantAPIData = it.tenantAPIData.immutableJsonMap(),
                            objectSelections = it.objectSelections?.immutableSnapshot(),
                            querySelections = it.querySelections?.immutableSnapshot(),
                        )
                    },
                ),
                namedFragments = Collections.unmodifiableList(namedFragments),
            )

        private fun SelectionsBlockConfig.immutableSnapshot(): SelectionsBlockConfig =
            copy(
                variablesProviders = Collections.unmodifiableList(
                    variablesProviders.map {
                        it.copy(providedVariables = Collections.unmodifiableMap(it.providedVariables))
                    },
                ),
            )

        private fun Map<String, Any?>.immutableJsonMap(): Map<String, Any?> = Collections.unmodifiableMap(mapValues { immutableJsonValue(it.value) })

        private fun immutableJsonValue(value: Any?): Any? =
            when (value) {
                is Map<*, *> -> Collections.unmodifiableMap(value.mapValues { immutableJsonValue(it.value) })
                is List<*> -> Collections.unmodifiableList(value.map(::immutableJsonValue))
                else -> value
            }
    }
}
