[versions]
# Project
project = "INCLUDED"
pluginIdPrefix = "com.airbnb.viaduct"

# Libraries
assertj = "3.27.7"
asm = "9.7.1"
antlr-st4 = "4.3.1"
binaryCompatibility = "0.18.1"
caffeine = "2.9.3"
classgraph = "4.8.177"
clikt = "3.5.4"
graphql-java = "26.0"
graphql-java-extension = "24.0"
guava = "33.3.1-jre"
checker = "3.33.0"
guice = "6.0.0"
jackson = "2.17.3"
javassist = "3.28.0-GA"
ktor = "3.0.3"
javax-inject = "1"
jmh = "1.37"
junit5 = "5.11.3"
kotest = "5.9.1"
kotlin = "1.9.25"
ksp = "1.9.25-1.0.20"
kotlinx = "1.8.1"
kotlinx-debug = "1.8.1"
kotlinx-metadata = "0.9.0"
mockk-jvm = "1.13.3"
grpc = "1.66.0"
grpc-kotlin = "1.4.1"
protobuf = "3.25.1"
slf4j = "2.0.7"
jspecify = "1.0.0"
micrometer = "1.10.8"

# Plugins
ktlintPluginVersion = "12.1.2"
ktlintVersion = "1.2.1"
detekt = "1.23.6"
errorprone = "2.36.0"
errorpronePlugin = "4.1.0"
googleJavaFormat = "1.26.0"
jacoco = "0.8.12"
nullaway = "0.12.9"
dokka = "2.0.0"
gradle-maven-publish = "0.34.0"
develocity = "3.19.2"
foojay-resolver-convention = "0.8.0"
idea-gradle-plugin = "1.3"
shadow = "8.3.9"
spotless = "7.0.2"
cyclonedx-gradle = "1.10.0"
jk1-license-report = "2.9"
test-retry = "1.6.5"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlintPlugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPluginVersion" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }
jacoco = { id = "jacoco", version.ref = "jacoco" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokkaJavaDoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish" }
develocity = { id = "com.gradle.develocity", version.ref = "develocity" }
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver-convention" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cyclonedx-gradle" }
jk1-license-report = { id = "com.github.jk1.dependency-license-report", version.ref = "jk1-license-report" }
test-retry = { id = "org.gradle.test-retry", version.ref = "test-retry" }

[libraries]
# Project
viaduct-engine-api = { module = "com.airbnb.viaduct.engine:api", version.ref = "project" }
viaduct-engine-runtime = { module = "com.airbnb.viaduct.engine:runtime", version.ref = "project" }
viaduct-engine-wiring = { module = "com.airbnb.viaduct.engine:wiring", version.ref = "project" }
viaduct-tenant-api = { module = "com.airbnb.viaduct.tenant:api", version.ref = "project" }
viaduct-tenant-runtime = { module = "com.airbnb.viaduct.tenant:runtime", version.ref = "project" }
viaduct-tenant-codegen = { module = "com.airbnb.viaduct.tenant:codegen", version.ref = "project" }
viaduct-tenant-ksp = { module = "com.airbnb.viaduct.tenant:ksp", version.ref = "project" }
viaduct-tenant-validation = { module = "com.airbnb.viaduct.tenant:validation", version.ref = "project" }
viaduct-tenant-wiring = { module = "com.airbnb.viaduct.tenant:wiring", version.ref = "project" }
viaduct-tenant-shared = { module = "com.airbnb.viaduct.tenant:shared", version.ref = "project" }

viaduct-javaapi-api = { module = "com.airbnb.viaduct.javaapi:api", version.ref = "project" }
viaduct-javaapi-codegen = { module = "com.airbnb.viaduct.javaapi:codegen", version.ref = "project" }
viaduct-javaapi-registry-apt = { module = "com.airbnb.viaduct.javaapi:registry-apt", version.ref = "project" }
viaduct-javaapi-runtime = { module = "com.airbnb.viaduct.javaapi:runtime", version.ref = "project" }

viaduct-service-api = { module = "com.airbnb.viaduct.service:api", version.ref = "project" }
viaduct-service-runtime = { module = "com.airbnb.viaduct.service:runtime", version.ref = "project" }
viaduct-service-wiring = { module = "com.airbnb.viaduct.service:wiring", version.ref = "project" }

viaduct-shared-apiannotations = { module = "com.airbnb.viaduct.shared:apiannotations", version.ref = "project" }
viaduct-shared-arbitrary = { module = "com.airbnb.viaduct.shared:arbitrary", version.ref = "project" }
viaduct-shared-arbitrary-cli = { module = "com.airbnb.viaduct.shared:arbitrary-cli", version.ref = "project" }
viaduct-shared-bootstrap = { module = "com.airbnb.viaduct.shared:bootstrap", version.ref = "project" }
viaduct-shared-codegen = { module = "com.airbnb.viaduct.shared:codegen", version.ref = "project" }
viaduct-shared-dataloader = { module = "com.airbnb.viaduct.shared:dataloader", version.ref = "project" }
viaduct-shared-deferred = { module = "com.airbnb.viaduct.shared:deferred", version.ref = "project" }
viaduct-shared-graphql = { module = "com.airbnb.viaduct.shared:graphql", version.ref = "project" }
viaduct-shared-invariants = { module = "com.airbnb.viaduct.shared:invariants", version.ref = "project" }
viaduct-shared-mapping = { module = "com.airbnb.viaduct.shared:mapping", version.ref = "project" }
viaduct-shared-utils = { module = "com.airbnb.viaduct.shared:utils", version.ref = "project" }
viaduct-shared-viaductschema = { module = "com.airbnb.viaduct.shared:viaductschema", version.ref = "project" }
viaduct-errors = { module = "com.airbnb.viaduct.shared:errors", version.ref = "project" }

viaduct-gradle-plugins-common = { module = "com.airbnb.viaduct.gradle:common", version.ref = "project" }

viaduct-api = { module = "com.airbnb.viaduct:api", version.ref = "project" }
viaduct-runtime = { module = "com.airbnb.viaduct:runtime", version.ref = "project" }
viaduct-buildtime = { module = "com.airbnb.viaduct:buildtime", version.ref = "project" }

viaduct-x-remoteresolvers = { module = "com.airbnb.viaduct:remoteresolvers", version.ref = "project" }

# Kotlin
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-binary-compatibility-validator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "binaryCompatibility" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug", version.ref = "kotlinx-debug" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx" }
kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinx-metadata" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Dokka
dokka-all-modules-page-plugin = { module = "org.jetbrains.dokka:all-modules-page-plugin", version.ref = "dokka" }

# Other libraries
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
antlr-st4 = { module = "org.antlr:ST4", version.ref = "antlr-st4" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
clikt-jvm = { module = "com.github.ajalt.clikt:clikt-jvm", version.ref = "clikt" }
graphql-java = { module = "com.graphql-java:graphql-java", version.ref = "graphql-java" }
graphql-java-extension = { module = "com.graphql-java:graphql-java-extended-scalars", version.ref = "graphql-java-extension" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-module = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
idea-gradle-plugin = { module = "org.jetbrains.gradle.plugin.idea-ext:org.jetbrains.gradle.plugin.idea-ext.gradle.plugin", version.ref = "idea-gradle-plugin" }

# gRPC and Protocol Buffers
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-core = { module = "io.grpc:grpc-core", version.ref = "grpc" }
grpc-inprocess = { module = "io.grpc:grpc-inprocess", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
# Testing
guava = { module = "com.google.guava:guava", version.ref = "guava" }
io-mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk-jvm" }
io-mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk-jvm" }
jmh-annotation-processor = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
junit = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }                               # version intentionally not specified
kotest-assertions-shared = { module = "io.kotest:kotest-assertions-shared", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-common-jvm = { module = "io.kotest:kotest-common-jvm", version.ref = "kotest" }
kotest-property-jvm = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker" }

# Linting
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
ktlint-rule-engine-core = { module = "com.pinterest.ktlint:ktlint-rule-engine-core", version.ref = "ktlintVersion" }
ktlint-cli-ruleset-core = { module = "com.pinterest.ktlint:ktlint-cli-ruleset-core", version.ref = "ktlintVersion" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
