package viaduct.graphql.schema.validation

/**
 * Standard error codes for schema validation rules.
 *
 * Using constants ensures consistency and enables IDE support for
 * code completion and refactoring.
 */
object ValidationErrorCodes {
    // NoSubscriptionsRule
    const val SUBSCRIPTION_NOT_ALLOWED = "SUBSCRIPTION_NOT_ALLOWED"

    // NoCustomScalarsRule
    const val CUSTOM_SCALAR_NOT_ALLOWED = "CUSTOM_SCALAR_NOT_ALLOWED"

    // ApplicationOnlyDefinitionsRule
    const val DIRECTIVE_DEFINED_IN_MODULE = "DIRECTIVE_DEFINED_IN_MODULE"
    const val SCALAR_DEFINED_IN_MODULE = "SCALAR_DEFINED_IN_MODULE"

    // BackingDataFieldsRule
    const val BACKING_DATA_MISSING_DIRECTIVE = "BACKING_DATA_MISSING_DIRECTIVE"
    const val BACKING_DATA_MISSING_TYPE = "BACKING_DATA_MISSING_TYPE"
    const val BACKING_DATA_ON_INPUT_FIELD = "BACKING_DATA_ON_INPUT_FIELD"
    const val BACKING_DATA_ON_INTERFACE_FIELD = "BACKING_DATA_ON_INTERFACE_FIELD"
    const val BACKING_DATA_IMPLEMENTED_INTERFACE_FIELD = "BACKING_DATA_IMPLEMENTED_INTERFACE_FIELD"

    // IdOfTypeValidationRule
    const val ID_OF_TYPE_NOT_FOUND = "ID_OF_TYPE_NOT_FOUND"
    const val ID_OF_TYPE_NOT_NODE = "ID_OF_TYPE_NOT_NODE"

    // NamespaceTypeConstraintsRule
    const val NAMESPACE_TYPE_FIELD_HAS_ARGS = "NAMESPACE_TYPE_FIELD_HAS_ARGS"
    const val NAMESPACE_TYPE_FIELD_IS_LIST = "NAMESPACE_TYPE_FIELD_IS_LIST"
    const val NAMESPACE_TYPE_FIELD_IS_NON_NULL = "NAMESPACE_TYPE_FIELD_IS_NON_NULL"
    const val NAMESPACE_TYPE_IN_UNION = "NAMESPACE_TYPE_IN_UNION"
    const val NAMESPACE_TYPE_PARENT_COUNT_NOT_ONE = "NAMESPACE_TYPE_PARENT_COUNT_NOT_ONE"
    const val NAMESPACE_TYPE_INVALID_PARENT = "NAMESPACE_TYPE_INVALID_PARENT"
    const val NAMESPACE_TYPE_FIELD_HAS_CONFLICTING_RESOLVER = "NAMESPACE_TYPE_FIELD_HAS_CONFLICTING_RESOLVER"
    const val NAMESPACE_TYPE_HAS_CONFLICTING_DIRECTIVE = "NAMESPACE_TYPE_HAS_CONFLICTING_DIRECTIVE"

    // ParentFieldConstraintsRule
    const val PARENT_FIELD_HAS_ARGS = "PARENT_FIELD_HAS_ARGS"
    const val PARENT_FIELD_IS_LIST = "PARENT_FIELD_IS_LIST"
    const val PARENT_FIELD_TYPE_NOT_COMPOSITE = "PARENT_FIELD_TYPE_NOT_COMPOSITE"
    const val PARENT_FIELD_ON_NON_OUTPUT_TYPE = "PARENT_FIELD_ON_NON_OUTPUT_TYPE"
    const val PARENT_FIELD_ON_INTERFACE = "PARENT_FIELD_ON_INTERFACE"
    const val PARENT_FIELD_IMPLEMENTED_INTERFACE_FIELD = "PARENT_FIELD_IMPLEMENTED_INTERFACE_FIELD"
    const val PARENT_FIELD_HAS_CONFLICTING_RESOLVER = "PARENT_FIELD_HAS_CONFLICTING_RESOLVER"
    const val PARENT_FIELD_TARGET_HAS_SELECTIVE_RESOLVER = "PARENT_FIELD_TARGET_HAS_SELECTIVE_RESOLVER"
    const val PARENT_FIELD_CHILD_HAS_AMBIGUOUS_PARENT = "PARENT_FIELD_CHILD_HAS_AMBIGUOUS_PARENT"

    // FieldArgumentsRequireResolverRule
    const val FIELD_WITH_ARGS_MISSING_RESOLVER = "FIELD_WITH_ARGS_MISSING_RESOLVER"

    // ConnectionTypeStructureRule
    const val CONNECTION_MISSING_EDGES_FIELD = "CONNECTION_MISSING_EDGES_FIELD"
    const val CONNECTION_EDGES_TYPE_NOT_EDGE = "CONNECTION_EDGES_TYPE_NOT_EDGE"
    const val CONNECTION_MISSING_PAGE_INFO_FIELD = "CONNECTION_MISSING_PAGE_INFO_FIELD"
    const val CONNECTION_PAGE_INFO_MUST_BE_NON_NULL = "CONNECTION_PAGE_INFO_MUST_BE_NON_NULL"

    // ConnectionEdgeStructureRule
    const val EDGE_MISSING_NODE_FIELD = "EDGE_MISSING_NODE_FIELD"

    // ConnectionPageInfoRule
    const val PAGE_INFO_MISSING_REQUIRED_FIELD = "PAGE_INFO_MISSING_REQUIRED_FIELD"
    const val PAGE_INFO_BOOLEAN_FIELD_MUST_BE_NON_NULL_BOOLEAN = "PAGE_INFO_BOOLEAN_FIELD_MUST_BE_NON_NULL_BOOLEAN"
    const val PAGE_INFO_CURSOR_MUST_BE_NULLABLE = "PAGE_INFO_CURSOR_MUST_BE_NULLABLE"
    const val PAGE_INFO_EXTRA_FIELDS = "PAGE_INFO_EXTRA_FIELDS"
    const val PAGE_INFO_FIELD_HAS_ARGS = "PAGE_INFO_FIELD_HAS_ARGS"
    const val PAGE_INFO_IMPLEMENTS_INTERFACE = "PAGE_INFO_IMPLEMENTS_INTERFACE"
    const val PAGE_INFO_IN_UNION = "PAGE_INFO_IN_UNION"

    // ConnectionArgumentsNullabilityRule
    const val CONNECTION_ARG_MUST_BE_NULLABLE = "CONNECTION_ARG_MUST_BE_NULLABLE"

    // PageInfoLocationRule
    const val PAGE_INFO_DEFINED_IN_MODULE = "PAGE_INFO_DEFINED_IN_MODULE"

    // NoCrossModuleInputExtensionsRule
    const val CROSS_MODULE_INPUT_EXTENSION = "CROSS_MODULE_INPUT_EXTENSION"
    const val APPBASE_INPUT_EXTENSION = "APPBASE_INPUT_EXTENSION"

    // StructuralDirectivesOnBaseTypeRule
    const val STRUCTURAL_DIRECTIVE_ON_EXTENSION = "STRUCTURAL_DIRECTIVE_ON_EXTENSION"

    // ScopeDirectivesRule
    const val SCOPE_EXTENSION_EXPANDS_BASE = "SCOPE_EXTENSION_EXPANDS_BASE"
    const val UNION_EXTENSION_SCOPE_INTERSECTION_MISMATCH = "UNION_EXTENSION_SCOPE_INTERSECTION_MISMATCH"
    const val IMPLEMENTED_INTERFACE_EXTENSION_SCOPE_MISMATCH = "IMPLEMENTED_INTERFACE_EXTENSION_SCOPE_MISMATCH"
    const val IMPLEMENTED_INTERFACE_FIELD_SCOPE_MISSING = "IMPLEMENTED_INTERFACE_FIELD_SCOPE_MISSING"
    const val OBJECT_OR_INTERFACE_EXTENSION_SCOPE_DIRECTIVE_MISSING = "OBJECT_OR_INTERFACE_EXTENSION_SCOPE_DIRECTIVE_MISSING"
    const val OBJECT_OR_INTERFACE_SCOPE_WITHOUT_FIELDS = "OBJECT_OR_INTERFACE_SCOPE_WITHOUT_FIELDS"
    const val TENANT_LOCAL_FIELD_TYPE_NOT_SCALAR = "TENANT_LOCAL_FIELD_TYPE_NOT_SCALAR"
    const val TENANT_LOCAL_INTERFACE_FIELD = "TENANT_LOCAL_INTERFACE_FIELD"
    const val TENANT_LOCAL_IMPLEMENTED_INTERFACE_FIELD = "TENANT_LOCAL_IMPLEMENTED_INTERFACE_FIELD"

    // CrossModuleExtensionFieldsResolverRule
    const val CROSS_MODULE_EXTENSION_FIELD_MISSING_RESOLVER = "CROSS_MODULE_EXTENSION_FIELD_MISSING_RESOLVER"

    // NoResolverOnInterfaceFieldsRule
    const val RESOLVER_ON_INTERFACE_FIELD = "RESOLVER_ON_INTERFACE_FIELD"

    // NodeInterfaceIdConsistencyRule
    const val NODE_INTERFACE_ID_INCONSISTENT = "NODE_INTERFACE_ID_INCONSISTENT"

    // NoTypeResolverOnNonNodeObjectsRule
    const val RESOLVER_ON_NON_NODE_OBJECT = "RESOLVER_ON_NON_NODE_OBJECT"
}
