package viaduct.tenant.codegen.bytecode.testschema

import graphql.schema.idl.SchemaParser
import graphql.schema.idl.UnExecutableSchemaGenerator
import java.io.File
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions.assertDoesNotThrow
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertDoesNotThrow
import viaduct.codegen.utils.JavaName
import viaduct.engine.api.EngineSchema
import viaduct.graphql.schema.ViaductSchema as ViaductGraphQLSchema
import viaduct.graphql.schema.graphqljava.extensions.fromTypeDefinitionRegistry
import viaduct.graphql.schema.graphqljava.readTypes
import viaduct.graphql.utils.DefaultSchemaFactory
import viaduct.invariants.FailureCollector
import viaduct.tenant.codegen.bytecode.CodeGenArgs
import viaduct.tenant.codegen.bytecode.GRTClassFilesBuilder
import viaduct.tenant.codegen.bytecode.config.ViaductBaseTypeMapper
import viaduct.tenant.codegen.bytecode.config.hashForSharding
import viaduct.tenant.codegen.bytecode.exercise.ClassResolver
import viaduct.tenant.codegen.bytecode.exercise.Exerciser
import viaduct.tenant.codegen.bytecode.util.assumedClassesForCodegen
import viaduct.utils.timer.Timer

/** End-to-end tests of generated byte codes for the test schema. */
@OptIn(ExperimentalCoroutinesApi::class)
class SchemaDrivenTests {
    private fun prepareSchemaFiles(): List<File> =
        listOf("graphql/bytecode_test_schema.graphqls", "graphql/classic.graphqls")
            .map { resourcePath ->
                val resourceStream = this::class.java.classLoader.getResourceAsStream(resourcePath)
                    ?: error("Resource not found: $resourcePath")
                val tempFile = File.createTempFile("schema-", ".graphqls")
                tempFile.deleteOnExit()
                tempFile.outputStream().use { output ->
                    resourceStream.use { input ->
                        input.copyTo(output)
                    }
                }
                tempFile
            }

    @Test
    fun reflectionDrivenExercisesV2() =
        runTest {
            val failures = FailureCollector()

            val sdl = DefaultSchemaFactory.getDefaultSDL(
                existingSDLFiles = prepareSchemaFiles(),
                includeNodeDefinition = DefaultSchemaFactory.IncludeNodeSchema.Always,
                includeNodeQueries = DefaultSchemaFactory.IncludeNodeSchema.Never
            )

            val schema = ViaductGraphQLSchema.fromTypeDefinitionRegistry(SchemaParser().parse(sdl))
            val graphqlSchema = EngineSchema(UnExecutableSchemaGenerator.makeUnExecutableSchema(readTypes(sdl)))

            val args = prepareCodeGenArgs(schema, "viaduct.api.grts")
            val builder = GRTClassFilesBuilder(args)
                .addAll(schema)

            // V2/modern tests should use ViaductBaseTypeMapper
            // Note: V2/modern code uses parameter-passing, not cfg.baseTypeMapper
            val classLoader = builder.buildClassLoader()
            val exerciser = Exerciser(
                check = failures,
                classResolver = ClassResolver.fromClassLoader(JavaName("viaduct.api.grts"), classLoader),
                schema = schema,
                graphqlSchema = graphqlSchema,
            )
            exerciser.exerciseGeneratedCodeV2()
            if (!failures.isEmpty) {
                println("Test failures found:")
                failures.toListOfErrors().forEach { println(it) }
            }
            assertTrue(failures.isEmpty, "Expected no failures, but found:\n${failures.joinToString("\n")}")
        }

    private fun prepareCodeGenArgs(
        schema: ViaductGraphQLSchema,
        pkgForGeneratedClasses: String
    ): CodeGenArgs =
        CodeGenArgs(
            moduleName = null,
            pkgForGeneratedClasses,
            includeIneligibleTypesForTestingOnly = false,
            excludeCrossModuleFields = false,
            javaTargetVersion = null,
            workerNumber = 0,
            workerCount = 1,
            timer = Timer(),
            baseTypeMapper = ViaductBaseTypeMapper(schema),
        )

    /**
     * Regression test: codegen must not throw when a schema contains custom scalars absent from
     * [baseGraphqlScalarTypeMapping] (e.g. scalars with anonymized names like those in large-schema-4).
     *
     * Two fixes are required together:
     * 1. [GRTClassFilesBuilder.isGenerated] must return `false` for scalars so that
     *    [GRTClassFilesBuilderBase.addSchemaGRTReference] doesn't return early and skip registering
     *    a Javassist ClassPool placeholder for the scalar.
     * 2. [ViaductBaseTypeMapper.addSchemaGRTReference] must handle [EngineSchema.Scalar] so that
     *    the placeholder is actually registered — previously the `when` had no `Scalar` branch and
     *    silently did nothing.
     *
     * Without both fixes, `buildClassLoader` throws `javassist.NotFoundException` for any field
     * whose type is an unmapped custom scalar.
     */
    @Test
    fun `buildClassLoader succeeds with custom scalar types`() {
        val sdl = """
            scalar CustomScalar
            type Query {
                customField: CustomScalar
            }
        """.trimIndent()

        val schema = ViaductGraphQLSchema.fromTypeDefinitionRegistry(SchemaParser().parse(sdl))
        val args = prepareCodeGenArgs(schema, "viaduct.api.grts")

        assertDoesNotThrow {
            GRTClassFilesBuilder(args)
                .addAll(schema)
                .buildClassLoader()
        }
    }

    @Test
    fun `buildClassLoader succeeds for a soft getter overriding a primitive interface field`() {
        val sdl = """
            interface Event {
                seqNumber: Int!
            }
            type Query {
                event: ActivityClaimEvent
            }
            type ActivityClaimEvent implements Event {
                seqNumber: Int!
            }
        """.trimIndent()

        val schema = ViaductGraphQLSchema.fromTypeDefinitionRegistry(SchemaParser().parse(sdl))
        val args = prepareCodeGenArgs(schema, "viaduct.api.grts")

        assertDoesNotThrow {
            GRTClassFilesBuilder(args)
                .addAll(schema)
                .buildClassLoader()
        }
    }

    /**
     * Regression test: when a @connection type and its @edge type are generated by different
     * workers (workerCount > 1), the cross-shard placeholder for the edge type must include a
     * `public static final INSTANCE` field so that the generated ConnectionBuilder super-call
     * (`EdgeType$Reflection.INSTANCE`) can be compiled by Javassist.
     *
     * Without [viaduct.codegen.ct.ExternalClassWrapper.Nested.hasInstanceField] = true on the
     * Reflection nested class placeholder, and without an explicit cast to REFLECTED_TYPE in the
     * super-call, Javassist threw "cannot find field INSTANCE" / "cannot find constructor" when
     * the edge type was assigned to a different build shard than the connection type.
     */
    @Test
    fun `buildClassLoader succeeds when connection edge type is in a different shard`() {
        // FooConnection and FooEdge are chosen so they hash to different shards with workerCount=2.
        // hashForSharding() % 2 == sum-of-char-values % 2 (since 31^k is always odd).
        // "FooConnection" char-sum = 1332 (even → shard 0), "FooEdge" char-sum = 665 (odd → shard 1).
        val sdl = """
            directive @connection on OBJECT
            directive @edge on OBJECT
            type Query { nop: Int }
            type FooConnection @connection {
                edges: [FooEdge]
            }
            type FooEdge @edge {
                cursor: String!
                node: Foo
            }
            type Foo {
                name: String
            }
        """.trimIndent()

        val schema = ViaductGraphQLSchema.fromTypeDefinitionRegistry(SchemaParser().parse(sdl))

        // Sanity-check that the chosen names really do split across shards with workerCount=2.
        // If this assertion ever fails, the type names must be updated to restore the split.
        val workerCount = 2
        assertEquals(
            0,
            schema.types["FooConnection"]!!.hashForSharding() % workerCount,
            "FooConnection must hash to shard 0 for this test to exercise the cross-shard path"
        )
        assertEquals(
            1,
            schema.types["FooEdge"]!!.hashForSharding() % workerCount,
            "FooEdge must hash to shard 1 for this test to exercise the cross-shard path"
        )

        // Run codegen from worker 0's perspective: FooConnection is generated here, FooEdge is not.
        // The generated ConnectionBuilder references FooEdge$Reflection.INSTANCE, so the
        // cross-shard placeholder for FooEdge must expose that field.
        val args = prepareCodeGenArgs(schema, "test.pkg").copy(
            workerCount = workerCount,
            workerNumber = 0,
        )

        assertDoesNotThrow("buildClassLoader must not throw when edge type is in a different shard") {
            GRTClassFilesBuilder(args).addAll(schema).buildClassLoader()
        }
    }

    @Test
    fun invariantChecker() {
        // Call KmContext.check to check invariants of result from loadGraphQLSchema
        // Classic test should use AirbnbBaseTypeMapper

        val sdl = DefaultSchemaFactory.getDefaultSDL(
            existingSDLFiles = prepareSchemaFiles(),
            includeNodeDefinition = DefaultSchemaFactory.IncludeNodeSchema.Always,
            includeNodeQueries = DefaultSchemaFactory.IncludeNodeSchema.Never
        )

        val schema = ViaductGraphQLSchema.fromTypeDefinitionRegistry(SchemaParser().parse(sdl))

        val args = prepareCodeGenArgs(schema, "com.airbnb.viaduct.schema.generated")

        GRTClassFilesBuilder(args)
            .addAll(schema)
            .checkInvariants(allowedSuperTypes = assumedClassesForCodegen)
            .isEmpty
    }
}
