package viaduct.api.internal

import graphql.schema.GraphQLCompositeType
import graphql.schema.GraphQLEnumType
import graphql.schema.GraphQLFieldDefinition
import graphql.schema.GraphQLInterfaceType
import graphql.schema.GraphQLList
import graphql.schema.GraphQLObjectType
import graphql.schema.GraphQLScalarType
import graphql.schema.GraphQLType
import graphql.schema.GraphQLTypeUtil
import graphql.schema.GraphQLUnionType
import viaduct.api.globalid.GlobalID
import viaduct.apiannotations.Attribution
import viaduct.apiannotations.AttributionContext
import viaduct.engine.api.EngineObject
import viaduct.engine.api.EngineObjectData
import viaduct.engine.api.EngineObjectDataBuilder
import viaduct.errors.FrameworkException
import viaduct.errors.TenantUsageException
import viaduct.graphql.isGlobalID
import viaduct.service.api.spi.GlobalIDCodec

/**
 * A wrapper around EngineObjectDataBuilder that allows for setting fields by name for a given GraphQLObjectType.
 * This class is used by [ObjectBase.Builder] and [ViaductObjectBuilder] to build their underlying EngineObjectData.
 * When setting a field, the value is unwrapped to the appropriate type, e.g.,
 * unwrapping from the GRT to the EngineObjectData for GraphQLCompositeType fields.
 */
internal class EODBuilderWrapper(
    private val type: GraphQLObjectType,
    private val globalIDCodec: GlobalIDCodec
) {
    private val engineObjectDataBuilder = EngineObjectDataBuilder.from(type)

    @Attribution(AttributionContext.FRAMEWORK)
    fun getEngineObjectData() = engineObjectDataBuilder.build()

    /**
     * Either called by static builders which are code generated by framework,
     * which has no need to do comprehensive type checking, or called by dynamic
     * builders, which type checking has been done at the call site. Therefore,
     * we only use the minimum type checking needed for `unwrap` here for
     * efficiency reason.
     *
     * @param alias - Only used for use cases of unit tests needing to mock aliased results.
     *                Not to be used for production code or normal engine usage!
     */
    @Attribution(AttributionContext.FRAMEWORK)
    fun put(
        fieldName: String,
        value: Any?,
        alias: String? = null
    ) {
        val field = type.getField(fieldName)
        val fieldType = field.type ?: throw TenantUsageException(
            "Field ${field.name} not found on type ${type.name}"
        )
        engineObjectDataBuilder.put(alias ?: fieldName, unwrap(field, fieldType, value))
    }

    @Attribution(AttributionContext.FRAMEWORK)
    private fun unwrap(
        field: GraphQLFieldDefinition,
        fieldType: GraphQLType,
        value: Any?
    ): Any? {
        if (value == null) {
            if (GraphQLTypeUtil.isNonNull(fieldType)) {
                throw TenantUsageException(
                    "Got null builder value for non-null type ${GraphQLTypeUtil.simplePrint(fieldType)}"
                )
            }
            return null
        }

        return when (val unwrappedType = GraphQLTypeUtil.unwrapNonNull(fieldType)) {
            is GraphQLScalarType ->
                if (isGlobalID(field, type)) {
                    unwrapGlobalID(value)
                } else {
                    value
                }

            is GraphQLEnumType -> unwrapEnum(value)
            is GraphQLList -> unwrapList(field, unwrappedType, value)
            is GraphQLCompositeType -> unwrapObject(unwrappedType, value)
            else -> throw FrameworkException("Unexpected schema type ${GraphQLTypeUtil.simplePrint(unwrappedType)}")
        }
    }

    private fun unwrapEnum(value: Any): String {
        return when (value) {
            is Enum<*> -> value.name
            is String -> value // Allow strings for schema version skew tolerance
            else -> throw TenantUsageException("Got non-enum value $value for enum type (expected Enum or String)")
        }
    }

    private fun unwrapGlobalID(value: Any): String {
        val globalID = value as GlobalID<*>
        return globalIDCodec.serialize(globalID.type.name, globalID.internalID)
    }

    private fun unwrapList(
        field: GraphQLFieldDefinition,
        listType: GraphQLList,
        value: Any
    ): List<*> {
        if (value !is List<*>) {
            throw TenantUsageException("Got non-list builder value $value for list type")
        }
        return value.map {
            unwrap(field, GraphQLTypeUtil.unwrapOne(listType), it)
        }
    }

    @Suppress("SENSELESS_COMPARISON") // defensive null check
    private fun unwrapObject(
        expectedType: GraphQLCompositeType,
        value: Any
    ): EngineObject {
        val engineObject = when (value) {
            is ObjectBase -> value.__engineObject
            is EngineObjectData -> value
            else -> throw TenantUsageException("Expected ObjectBase or EngineObjectData for builder value, got $value")
        }
        // engineObject is null when an ObjectBase subclass is mocked in tests (Mockito/Objenesis
        // bypasses the constructor, leaving the field at its JVM default of null despite the
        // non-null Kotlin declaration). Skip type validation in that case.
        if (engineObject != null) {
            val actualTypeName = engineObject.type.name
            val valid = when (expectedType) {
                is GraphQLObjectType -> actualTypeName == expectedType.name
                is GraphQLInterfaceType -> engineObject.type.interfaces.any { it.name == expectedType.name }
                is GraphQLUnionType -> expectedType.isPossibleType(engineObject.type)
                // GraphQLCompositeType has exactly three concrete subtypes (object, interface, union).
                // This branch can only be reached if graphql-java adds a new subtype; blame the
                // framework, not the tenant.
                else -> throw FrameworkException("Unexpected composite type ${GraphQLTypeUtil.simplePrint(expectedType)}")
            }
            if (!valid) {
                throw TenantUsageException(
                    "Expected object of type ${expectedType.name} for builder value, got $actualTypeName"
                )
            }
        }
        return engineObject
    }
}
