package viaduct.arbitrary.graphql

import graphql.language.AstPrinter
import graphql.schema.idl.SchemaPrinter
import java.util.Collections
import java.util.IdentityHashMap
import viaduct.engine.api.CheckerResult
import viaduct.engine.api.Coordinate
import viaduct.engine.api.EngineObjectData
import viaduct.engine.api.EngineSchema
import viaduct.engine.api.RequiredSelectionSet
import viaduct.engine.api.RootFieldReference
import viaduct.engine.api.VariablesResolver
import viaduct.engine.api.spi.CheckerExecutor
import viaduct.engine.api.spi.FieldResolverExecutor
import viaduct.engine.api.spi.NodeResolverExecutor
import viaduct.graphql.utils.ParsedSelections
import viaduct.graphql.utils.SelectionsParserUtils.EntryPointFragmentName
import viaduct.service.api.SchemaId
import viaduct.service.api.Viaduct
import viaduct.service.runtime.StandardViaduct

/**
 * Human-readable snapshot of a Viaduct instance generated by the arbitrary GraphQL utilities.
 */
internal class ViaductDescriptor(
    private val schemas: List<SchemaDescriptor>,
    private val fieldResolvers: List<FieldResolverDescriptor> = emptyList(),
    private val nodeResolvers: List<NodeResolverDescriptor> = emptyList(),
    private val checkers: List<CheckerDescriptor> = emptyList(),
) {
    data class SchemaDescriptor(
        val schemaId: String,
        val sdl: String,
    )

    data class FieldResolverDescriptor(
        val coordinate: Coordinate,
        val resolverId: String,
        val className: String,
        val isBatching: Boolean,
        val isSelective: Boolean,
        val objectSelectionSet: RequiredSelectionSetDescriptor?,
        val querySelectionSet: RequiredSelectionSetDescriptor?,
        val calls: List<FieldResolverCallDescriptor>?,
    )

    data class FieldResolverCallDescriptor(
        val index: Int,
        val arguments: String,
        val selections: String?,
        val result: CallResultDescriptor,
        val time: String,
    )

    data class VariablesResolverCallDescriptor(
        val index: Int,
        val arguments: String,
        val objectData: String,
        val result: CallResultDescriptor,
        val time: String,
    )

    data class CheckerCallDescriptor(
        val index: Int,
        val checkerType: CheckerExecutor.CheckerType,
        val arguments: String,
        val objectDataMap: String,
        val result: CallResultDescriptor,
        val time: String,
    )

    sealed class CallResultDescriptor {
        data class Success(val value: String) : CallResultDescriptor()

        data class Failure(
            val className: String,
            val message: String?,
        ) : CallResultDescriptor()
    }

    data class NodeResolverDescriptor(
        val typeName: String,
        val className: String,
        val isBatching: Boolean,
        val isSelective: Boolean,
    )

    data class CheckerDescriptor(
        val coordinate: String,
        val className: String,
        val requiredSelectionSets: List<NamedRequiredSelectionSetDescriptor>,
        val calls: List<CheckerCallDescriptor>?,
    )

    data class NamedRequiredSelectionSetDescriptor(
        val name: String,
        val requiredSelectionSet: RequiredSelectionSetDescriptor?,
    )

    data class RequiredSelectionSetDescriptor(
        val typeName: String,
        val forChecker: Boolean,
        val selections: String,
        val variablesResolvers: List<VariablesResolverDescriptor>,
        val alreadyDescribed: Boolean = false,
    ) {
        override fun toString(): String = renderRequiredSelectionSetDescriptor()
    }

    data class VariablesResolverDescriptor(
        val variableNames: Set<String>,
        val className: String,
        val requiredSelectionSet: RequiredSelectionSetDescriptor?,
        val calls: List<VariablesResolverCallDescriptor>?,
    ) {
        override fun toString(): String = renderVariablesResolverDescriptor()
    }

    override fun toString(): String =
        buildString {
            line("Viaduct Descriptor")

            section("schemas", schemas) { schema ->
                line("  - ${schema.schemaId}")
                block("      ", schema.sdl)
            }

            section("field resolvers", fieldResolvers) { resolver ->
                line("  - ${resolver.coordinate.asString()}")
                line("      resolverId: ${resolver.resolverId}")
                line("      class: ${resolver.className}")
                line("      isBatching: ${resolver.isBatching}")
                line("      isSelective: ${resolver.isSelective}")
                appendRequiredSelectionSetDescriptor("      objectSelectionSet", resolver.objectSelectionSet)
                appendRequiredSelectionSetDescriptor("      querySelectionSet", resolver.querySelectionSet)
                appendFieldResolverCalls(resolver.calls)
            }

            section("node resolvers", nodeResolvers) { resolver ->
                line("  - ${resolver.typeName}")
                line("      class: ${resolver.className}")
                line("      isBatching: ${resolver.isBatching}")
                line("      isSelective: ${resolver.isSelective}")
            }

            section("checkers", checkers) { checker ->
                line("  - ${checker.coordinate}")
                line("      class: ${checker.className}")
                if (checker.requiredSelectionSets.isEmpty()) {
                    line("      requiredSelectionSets: <none>")
                } else {
                    line("      requiredSelectionSets:")
                    checker.requiredSelectionSets.forEach { named ->
                        appendRequiredSelectionSetDescriptor("        ${named.name}", named.requiredSelectionSet)
                    }
                }
                appendCheckerCalls(checker.calls)
            }
        }.trimEnd()

    private fun <T> StringBuilder.section(
        title: String,
        values: List<T>,
        render: StringBuilder.(T) -> Unit,
    ) {
        line()
        line("$title:")
        if (values.isEmpty()) {
            line("  <none>")
        } else {
            values.forEach { render(it) }
        }
    }

    private fun StringBuilder.block(
        indent: String,
        text: String,
    ) {
        text.lineSequence()
            .filter { it.isNotBlank() }
            .forEach { line("$indent$it") }
    }

    private fun StringBuilder.line(text: String = "") {
        append(text).append('\n')
    }

    companion object {
        private val schemaPrinter = SchemaPrinter()

        internal fun from(viaduct: Viaduct): ViaductDescriptor = checkNotNull(viaduct as? DescribedViaduct).descriptor()

        internal fun from(requiredSelectionSet: RequiredSelectionSet): RequiredSelectionSetDescriptor = describeRequiredSelectionSet(requiredSelectionSet, mutableSetOf())

        internal fun from(variablesResolver: VariablesResolver): VariablesResolverDescriptor = describeVariablesResolver(variablesResolver, mutableSetOf())

        internal fun fromGenerated(
            viaduct: Viaduct,
            config: GeneratedViaductDescriptorConfig,
        ): ViaductDescriptor =
            ViaductDescriptor(
                schemas = (viaduct as? StandardViaduct)?.schemaDescriptors()
                    ?: listOf(SchemaDescriptor(SchemaId.Base.toString(), schemaPrinter.print(config.schema.schema))),
                fieldResolvers = config.fieldResolverExecutors
                    .sortedBy { it.first.asString() }
                    .map { (coord, executor) -> executor.describe(coord, config.instrumentedFieldResolverFactory) },
                nodeResolvers = config.nodeResolverExecutors
                    .sortedBy { it.first }
                    .map { (_, executor) -> executor.describe },
                checkers = (
                    config.fieldCheckerExecutors.map { (coord, executor) -> "field ${coord.asString()}" to executor } +
                        config.typeCheckerExecutors.map { (typeName, executor) -> "type $typeName" to executor }
                )
                    .sortedBy { it.first }
                    .map { (coordinate, executor) -> executor.describe(coordinate) },
            )

        private fun StandardViaduct.schemaDescriptors(): List<SchemaDescriptor> =
            engineRegistry.getRegisteredSchemaIds()
                .sortedBy { it.toString() }
                .map { schemaId ->
                    SchemaDescriptor(
                        schemaId = schemaId.toString(),
                        sdl = schemaPrinter.print(getSchema(schemaId).schema),
                    )
                }

        private fun FieldResolverExecutor.describe(
            coord: Coordinate,
            instrumentedFieldResolverFactory: FieldResolver.Factory.Instrumented?,
        ): FieldResolverDescriptor =
            FieldResolverDescriptor(
                coordinate = coord,
                resolverId = resolverId,
                className = debugClassName(),
                isBatching = isBatching,
                isSelective = isSelective,
                objectSelectionSet = objectSelectionSet?.describeWithFreshContext(),
                querySelectionSet = querySelectionSet?.describeWithFreshContext(),
                calls = instrumentedFieldResolverFactory?.resolverOrNull(coord)?.describeCalls(),
            )

        private fun FieldResolver.Instrumented.describeCalls(): List<FieldResolverCallDescriptor> =
            recorder.log.mapIndexed { index, entry ->
                FieldResolverCallDescriptor(
                    index = index + 1,
                    arguments = describeValue(entry.arg.selector.arguments),
                    selections = entry.arg.selector.selections?.toFragment()?.document,
                    result = entry.result.fold(
                        onSuccess = { CallResultDescriptor.Success(describeValue(it)) },
                        onFailure = { it.describeFailure() },
                    ),
                    time = entry.time.toString(),
                )
            }

        private val NodeResolverExecutor.describe: NodeResolverDescriptor
            get() =
                NodeResolverDescriptor(
                    typeName = typeName,
                    className = debugClassName(),
                    isBatching = isBatching,
                    isSelective = isSelective,
                )

        private fun CheckerExecutor.describe(coordinate: String): CheckerDescriptor =
            CheckerDescriptor(
                coordinate = coordinate,
                className = debugClassName(),
                requiredSelectionSets = requiredSelectionSets
                    .toSortedMap()
                    .map { (name, rss) ->
                        NamedRequiredSelectionSetDescriptor(name, rss?.describeWithFreshContext())
                    },
                calls = (this as? viaduct.arbitrary.graphql.CheckerExecutor.Instrumented)?.describeCalls(),
            )

        private fun viaduct.arbitrary.graphql.CheckerExecutor.Instrumented.describeCalls(): List<CheckerCallDescriptor> =
            recorder.log.mapIndexed { index, entry ->
                CheckerCallDescriptor(
                    index = index + 1,
                    checkerType = entry.arg.checkerType,
                    arguments = describeValue(entry.arg.arguments),
                    objectDataMap = describeValue(entry.arg.objectDataMap),
                    result = entry.result.fold(
                        onSuccess = { CallResultDescriptor.Success(describeCheckerResult(it)) },
                        onFailure = { it.describeFailure() },
                    ),
                    time = entry.time.toString(),
                )
            }

        private fun RequiredSelectionSet.describeWithFreshContext(): RequiredSelectionSetDescriptor = describeRequiredSelectionSet(this, mutableSetOf())

        private fun describeRequiredSelectionSet(
            rss: RequiredSelectionSet,
            seen: MutableSet<RequiredSelectionSet.Id>,
        ): RequiredSelectionSetDescriptor {
            val alreadyDescriptored = !seen.add(rss.id)
            return RequiredSelectionSetDescriptor(
                typeName = rss.selections.typeName,
                forChecker = rss.forChecker,
                selections = rss.selections.describe(),
                variablesResolvers = if (alreadyDescriptored) {
                    emptyList()
                } else {
                    rss.variablesResolvers.map { describeVariablesResolver(it, seen) }
                },
                alreadyDescribed = alreadyDescriptored,
            )
        }

        private fun describeVariablesResolver(
            variablesResolver: VariablesResolver,
            seen: MutableSet<RequiredSelectionSet.Id>,
        ): VariablesResolverDescriptor =
            VariablesResolverDescriptor(
                variableNames = variablesResolver.variableNames,
                className = variablesResolver.debugClassName(),
                requiredSelectionSet = variablesResolver.requiredSelectionSet?.let {
                    describeRequiredSelectionSet(it, seen)
                },
                calls = (variablesResolver as? viaduct.arbitrary.graphql.VariablesResolver.Instrumented)
                    ?.describeCalls(),
            )

        private fun viaduct.arbitrary.graphql.VariablesResolver.Instrumented.describeCalls(): List<VariablesResolverCallDescriptor> =
            recorder.log.mapIndexed { index, entry ->
                VariablesResolverCallDescriptor(
                    index = index + 1,
                    arguments = describeValue(entry.arg.ctx.arguments),
                    objectData = describeValue(entry.arg.ctx.objectData),
                    result = entry.result.fold(
                        onSuccess = { CallResultDescriptor.Success(describeValue(it)) },
                        onFailure = { it.describeFailure() },
                    ),
                    time = entry.time.toString(),
                )
            }

        private fun Coordinate.asString(): String = "$first.$second"
    }
}

internal fun RequiredSelectionSet.describe(): ViaductDescriptor.RequiredSelectionSetDescriptor = ViaductDescriptor.from(this)

internal fun VariablesResolver.describe(): ViaductDescriptor.VariablesResolverDescriptor = ViaductDescriptor.from(this)

internal data class GeneratedViaductDescriptorConfig(
    val schema: EngineSchema,
    val fieldResolverExecutors: List<Pair<Coordinate, FieldResolverExecutor>>,
    val instrumentedFieldResolverFactory: FieldResolver.Factory.Instrumented?,
    val nodeResolverExecutors: List<Pair<String, NodeResolverExecutor>>,
    val fieldCheckerExecutors: Map<Coordinate, CheckerExecutor>,
    val typeCheckerExecutors: Map<String, CheckerExecutor>,
)

internal class DescribedViaduct(
    private val delegate: Viaduct,
    val descriptor: () -> ViaductDescriptor,
) : Viaduct by delegate

private fun FieldResolver.Factory.Instrumented.resolverOrNull(coord: Coordinate): FieldResolver.Instrumented? = resolvers[coord]

private fun Any.debugClassName(): String = this::class.qualifiedName ?: this::class.java.name

private fun ViaductDescriptor.RequiredSelectionSetDescriptor.renderRequiredSelectionSetDescriptor(): String =
    buildString {
        appendRequiredSelectionSetDescriptor(this@renderRequiredSelectionSetDescriptor, "")
    }.trimEnd()

private fun ViaductDescriptor.VariablesResolverDescriptor.renderVariablesResolverDescriptor(): String =
    buildString {
        appendVariablesResolverDescriptor(this@renderVariablesResolverDescriptor, "")
    }.trimEnd()

private fun StringBuilder.appendRequiredSelectionSetDescriptor(
    label: String,
    rss: ViaductDescriptor.RequiredSelectionSetDescriptor?,
) {
    if (rss == null) {
        line("$label: <none>")
        return
    }

    line("$label:")
    appendRequiredSelectionSetDescriptor(rss, label.leadingWhitespace() + "  ")
}

private fun StringBuilder.appendRequiredSelectionSetDescriptor(
    rss: ViaductDescriptor.RequiredSelectionSetDescriptor,
    indent: String,
) {
    line("${indent}type: ${rss.typeName}")
    line("${indent}forChecker: ${rss.forChecker}")
    if (rss.alreadyDescribed) {
        line("${indent}selections: <already described>")
        return
    }

    line("${indent}selections:")
    block("$indent  ", rss.selections)
    if (rss.variablesResolvers.isEmpty()) {
        line("${indent}variablesResolvers: <none>")
    } else {
        line("${indent}variablesResolvers:")
        rss.variablesResolvers.forEach { resolver ->
            appendVariablesResolverDescriptor(resolver, "$indent  ")
        }
    }
}

private fun StringBuilder.appendFieldResolverCalls(calls: List<ViaductDescriptor.FieldResolverCallDescriptor>?) {
    if (calls == null) {
        return
    }

    if (calls.isEmpty()) {
        line("      calls: <none>")
        return
    }

    line("      calls:")
    calls.forEach { call ->
        line("        - #${call.index}")
        line("          request:")
        line("            arguments:")
        block("              ", call.arguments)
        if (call.selections == null) {
            line("            selections: <none>")
        } else {
            line("            selections:")
            block("              ", call.selections)
        }
        line("          response:")
        appendCallResult(call.result, "            ")
        line("            time: ${call.time}")
    }
}

private fun StringBuilder.appendCheckerCalls(calls: List<ViaductDescriptor.CheckerCallDescriptor>?) {
    if (calls == null) {
        return
    }

    if (calls.isEmpty()) {
        line("      calls: <none>")
        return
    }

    line("      calls:")
    calls.forEach { call ->
        line("        - #${call.index}")
        line("          request:")
        line("            checkerType: ${call.checkerType}")
        line("            arguments:")
        block("              ", call.arguments)
        line("            objectDataMap:")
        block("              ", call.objectDataMap)
        line("          response:")
        appendCallResult(call.result, "            ")
        line("            time: ${call.time}")
    }
}

private fun StringBuilder.appendVariablesResolverDescriptor(
    resolver: ViaductDescriptor.VariablesResolverDescriptor,
    indent: String,
) {
    line("$indent- variables: ${resolver.variableNames.sorted()}")
    line("$indent  class: ${resolver.className}")
    appendRequiredSelectionSetDescriptor("$indent  requiredSelectionSet", resolver.requiredSelectionSet)
    appendVariablesResolverCalls(resolver.calls, "$indent  ")
}

private fun StringBuilder.appendVariablesResolverCalls(
    calls: List<ViaductDescriptor.VariablesResolverCallDescriptor>?,
    indent: String,
) {
    if (calls == null) {
        return
    }

    if (calls.isEmpty()) {
        line("${indent}calls: <none>")
        return
    }

    line("${indent}calls:")
    calls.forEach { call ->
        line("$indent  - #${call.index}")
        line("$indent    request:")
        line("$indent      arguments:")
        block("$indent        ", call.arguments)
        line("$indent      objectData:")
        block("$indent        ", call.objectData)
        line("$indent    response:")
        appendCallResult(call.result, "$indent      ")
        line("$indent      time: ${call.time}")
    }
}

private fun StringBuilder.appendCallResult(
    result: ViaductDescriptor.CallResultDescriptor,
    indent: String,
) {
    when (result) {
        is ViaductDescriptor.CallResultDescriptor.Success -> {
            line("${indent}success:")
            block("$indent  ", result.value)
        }
        is ViaductDescriptor.CallResultDescriptor.Failure -> {
            line("${indent}failure:")
            line("$indent  class: ${result.className}")
            line("$indent  message: ${result.message ?: "<none>"}")
        }
    }
}

private fun ParsedSelections.describe(): String =
    buildString {
        append(AstPrinter.printAst(selections).trim())
        val fragments = fragmentMap.values
            .filter { it.name != EntryPointFragmentName }
            .sortedBy { it.name }
        if (fragments.isNotEmpty()) {
            if (isNotEmpty()) append('\n')
            append("fragments:\n")
            fragments.forEach { fragment ->
                append(AstPrinter.printAst(fragment).trim()).append('\n')
            }
        }
    }.trimEnd()

private fun describeValue(value: Any?): String =
    describeValue(
        value,
        Collections.newSetFromMap(IdentityHashMap())
    )

private fun describeValue(
    value: Any?,
    seen: MutableSet<Int>,
): String =
    when (value) {
        null -> "null"
        is String -> "\"${value.escapeForDump()}\""
        is Number, is Boolean -> value.toString()
        is Map<*, *> -> describeMap(value, seen)
        is Iterable<*> -> describeIterable(value, seen)
        is Array<*> -> describeIterable(value.asList(), seen)
        is RootFieldReference -> describeRootFieldReference(value, seen)
        is EngineObjectData.Sync -> describeEngineObjectData(value, seen)
        is EngineObjectData -> "${value.debugClassName()}(<async>)"
        else -> value.toString()
    }

private fun describeRootFieldReference(
    value: RootFieldReference,
    seen: MutableSet<Int>,
): String =
    buildString {
        line("${value.debugClassName()} {")
        appendDumpEntry("  rootFieldPath: ", describeValue(value.rootFieldPath, seen))
        line("  type: ${value.type.name}")
        appendDumpEntry("  args: ", describeValue(value.args, seen))
        append("}")
    }

private fun describeMap(
    value: Map<*, *>,
    seen: MutableSet<Int>,
): String {
    if (value.isEmpty()) {
        return "{}"
    }

    return buildString {
        line("{")
        value.entries
            .sortedBy { it.key.toString() }
            .forEach { (key, mapValue) ->
                appendDumpEntry("  ${describeValue(key, seen)}: ", describeValue(mapValue, seen))
            }
        append("}")
    }
}

private fun describeIterable(
    value: Iterable<*>,
    seen: MutableSet<Int>,
): String {
    val values = value.toList()
    if (values.isEmpty()) {
        return "[]"
    }

    return buildString {
        line("[")
        values.forEach {
            appendDumpEntry("  - ", describeValue(it, seen))
        }
        append("]")
    }
}

private fun describeEngineObjectData(
    value: EngineObjectData.Sync,
    seen: MutableSet<Int>,
): String {
    val identity = System.identityHashCode(value)
    if (!seen.add(identity)) {
        return "${value.type.name}(<cycle>)"
    }

    return try {
        val selections = value.getSelections().toList().sorted()
        if (selections.isEmpty()) {
            "${value.type.name} {}"
        } else {
            buildString {
                line("${value.type.name} {")
                selections.forEach { selection ->
                    val fieldValue = runCatching { value.getOrNull(selection) }
                    val renderedValue = fieldValue.fold(
                        onSuccess = { describeValue(it, seen) },
                        onFailure = { "<failed to read: ${it.debugClassName()}: ${it.message ?: "<none>"}>" },
                    )
                    appendDumpEntry("  $selection: ", renderedValue)
                }
                append("}")
            }
        }
    } finally {
        seen.remove(identity)
    }
}

private fun describeCheckerResult(result: CheckerResult): String =
    when (result) {
        is CheckerResult.Success -> "Success"
        is CheckerResult.Error -> buildString {
            line("Error {")
            line("  class: ${result.error.debugClassName()}")
            line("  message: ${result.error.message ?: "<none>"}")
            append("}")
        }
    }

private fun Throwable.describeFailure(): ViaductDescriptor.CallResultDescriptor.Failure =
    ViaductDescriptor.CallResultDescriptor.Failure(
        className = debugClassName(),
        message = message,
    )

private fun StringBuilder.appendDumpEntry(
    prefix: String,
    value: String,
) {
    val lines = value.lines()
    append(prefix).appendLine(lines.first())
    lines.drop(1).forEach { line ->
        append(" ".repeat(prefix.length)).appendLine(line)
    }
}

private fun String.escapeForDump(): String =
    buildString {
        this@escapeForDump.forEach { char ->
            when (char) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(char)
            }
        }
    }

private fun String.leadingWhitespace(): String = takeWhile { it == ' ' }

private fun StringBuilder.block(
    indent: String,
    text: String,
) {
    text.lineSequence()
        .filter { it.isNotBlank() }
        .forEach { line("$indent$it") }
}

private fun StringBuilder.line(text: String = "") {
    append(text).append('\n')
}
